### ISSUE TITLE
支持cocoapods

### ISSUE THREAD

**Issue by djiangnz** [wfxiaolong/STWebViewController#1]
你好 能支持cocoapods 吗

**Comment by wfxiaolong** [comment]
好的，我添加一下...

**Comment by wfxiaolong** [comment]
你好，最近这些天出了事情，急缺钱，然后在努力赚钱中..所以，只能支持cocoapods也只能延后，而且，我也想重新封装一次...之前写得很不优雅，只是一个上午随便写的，为了满足功能需求...

**Comment by sicaboy** [comment]
+1

**Comment by sicaboy** [comment]
已经star咯。希望能发展成最大的webViewProgress。希望能有Swift2.0的封装

**Comment by wfxiaolong** [comment]
已经支持cocoapods.
最近会添加swift版本的支持.
目前progress是用的其它人的，后面会接着更新，感谢。🙏
